# Generated by Django 5.2.3 on 2025-06-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_student_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
