# Generated by Django 5.2.3 on 2025-06-21 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_student_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('teacher', 'name', 'subject')},
        ),
    ]
